azs:
- name: z1
  cloud_properties:
    zone: asia-south1-a

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: large
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 50
    root_disk_type: pd-ssd

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/26
    gateway: 10.0.0.1
    azs: [z1]
    dns: [8.8.8.8,8.8.4.4]
    static: [10.0.0.12]
    reserved: [10.0.0.1,10.0.0.2,10.0.0.3,10.0.0.4,10.0.0.5,10.0.0.6,10.0.0.7,10.0.0.8,10.0.0.9,10.0.0.10,10.0.0.11]
    cloud_properties:
      network_name: am-pcf-pcf-network
      subnetwork_name: am-pcf-management-subnet
      ephemeral_external_ip: true
      tags: [internal, concourse]
- name: vip
  type: vip

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
